#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_Door

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AnimBP_Door.AnimBP_Door_C
// 0x0160 (0x0420 - 0x02C0)
class UAnimBP_Door_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02C8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x02F8(0x0080)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0378(0x0048)()
	struct FTransform                             LeftHandTransform;                                 // 0x03C0(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FTransform                             RightHandTransform;                                // 0x03F0(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void ExecuteUbergraph_AnimBP_Door(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AnimBP_Door_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AnimBP_Door_C")
	}
	static class UAnimBP_Door_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimBP_Door_C>();
	}
};
DUMPER7_ASSERTS_UAnimBP_Door_C;

}

