#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CardReaderFunc

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "E_PersonalTypes_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CardReaderFunc.BP_CardReaderFunc_C
// 0x0000 (0x0028 - 0x0028)
class UBP_CardReaderFunc_C final : public UBlueprintFunctionLibrary
{
public:
	static struct FLinearColor GetColorByIndex(int32 Index_0, class UObject* __WorldContext);
	static void GetPersonalTextByType(E_PersonalTypes PersonalType, class UObject* __WorldContext, class FText* Text);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CardReaderFunc_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CardReaderFunc_C")
	}
	static class UBP_CardReaderFunc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CardReaderFunc_C>();
	}
};
DUMPER7_ASSERTS_UBP_CardReaderFunc_C;

}

