#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_callButton

#include "Basic.hpp"

#include "BP_callButton_classes.hpp"
#include "BP_callButton_parameters.hpp"


namespace SDK
{

// Function BP_callButton.BP_callButton_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_callButton_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_callButton_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_callButton.BP_callButton_C.PressButton
// (BlueprintCallable, BlueprintEvent)

void ABP_callButton_C::PressButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_callButton_C", "PressButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_callButton.BP_callButton_C.TurnON
// (BlueprintCallable, BlueprintEvent)

void ABP_callButton_C::TurnON()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_callButton_C", "TurnON");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_callButton.BP_callButton_C.TurnOFF
// (BlueprintCallable, BlueprintEvent)

void ABP_callButton_C::TurnOFF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_callButton_C", "TurnOFF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_callButton.BP_callButton_C.OnActorUsed_1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_callButton_C::OnActorUsed_1(class ACharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_callButton_C", "OnActorUsed_1");

	Params::BP_callButton_C_OnActorUsed_1 Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_callButton.BP_callButton_C.ExecuteUbergraph_BP_callButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_callButton_C::ExecuteUbergraph_BP_callButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_callButton_C", "ExecuteUbergraph_BP_callButton");

	Params::BP_callButton_C_ExecuteUbergraph_BP_callButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

