#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Column

#include "Basic.hpp"

#include "BP_Column_classes.hpp"
#include "BP_Column_parameters.hpp"


namespace SDK
{

// Function BP_Column.BP_Column_C.FillMeshArrIndex
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<class UStaticMesh*>&       TargetArray                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const TArray<int32>&                    TargetArray2                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_Column_C::FillMeshArrIndex(const TArray<class UStaticMesh*>& TargetArray, const TArray<int32>& TargetArray2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Column_C", "FillMeshArrIndex");

	Params::BP_Column_C_FillMeshArrIndex Parms{};

	Parms.TargetArray = std::move(TargetArray);
	Parms.TargetArray2 = std::move(TargetArray2);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Column.BP_Column_C.GetRandomSeed
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class USceneComponent*                  Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRandomStream                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor)

struct FRandomStream ABP_Column_C::GetRandomSeed(class USceneComponent* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Column_C", "GetRandomSeed");

	Params::BP_Column_C_GetRandomSeed Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Column.BP_Column_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Column_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Column_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

