#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Cabinet_Base

#include "Basic.hpp"

#include "BP_Cabinet_Base_classes.hpp"
#include "BP_Cabinet_Base_parameters.hpp"


namespace SDK
{

// Function BP_Cabinet_Base.BP_Cabinet_Base_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Cabinet_Base_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cabinet_Base_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cabinet_Base.BP_Cabinet_Base_C.ExecuteUbergraph_BP_Cabinet_Base
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Cabinet_Base_C::ExecuteUbergraph_BP_Cabinet_Base(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cabinet_Base_C", "ExecuteUbergraph_BP_Cabinet_Base");

	Params::BP_Cabinet_Base_C_ExecuteUbergraph_BP_Cabinet_Base Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

