#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ElevatorButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ElevatorButton.BP_ElevatorButton_C
// 0x0028 (0x0270 - 0x0248)
class ABP_ElevatorButton_C final : public AInteractableActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0248(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh3;                                       // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh2;                                       // 0x0258(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          CanInteract;                                       // 0x0268(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void OnActorUsed(class ACharacter* Character);
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_ElevatorButton(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ElevatorButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ElevatorButton_C")
	}
	static class ABP_ElevatorButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ElevatorButton_C>();
	}
};
DUMPER7_ASSERTS_ABP_ElevatorButton_C;

}

