#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LightManager

#include "Basic.hpp"

#include "BP_LightManager_classes.hpp"
#include "BP_LightManager_parameters.hpp"


namespace SDK
{

// Function BP_LightManager.BP_LightManager_C.RemoveEntities
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_LightManager_C::RemoveEntities()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "RemoveEntities");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LightManager.BP_LightManager_C.GetTurnOffDelay
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Delay                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LightManager_C::GetTurnOffDelay(float* Delay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "GetTurnOffDelay");

	Params::BP_LightManager_C_GetTurnOffDelay Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Delay != nullptr)
		*Delay = Parms.Delay;
}


// Function BP_LightManager.BP_LightManager_C.SpawnEntities
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_LightManager_C::SpawnEntities()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "SpawnEntities");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LightManager.BP_LightManager_C.GetExitLocation
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APipe_Exit_C*                     Exit                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FTransform*                      Location                                               (Parm, OutParm, IsPlainOldData, NoDestructor)

void ABP_LightManager_C::GetExitLocation(class APipe_Exit_C* Exit, struct FTransform* Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "GetExitLocation");

	Params::BP_LightManager_C_GetExitLocation Parms{};

	Parms.Exit = Exit;

	UObject::ProcessEvent(Func, &Parms);

	if (Location != nullptr)
		*Location = std::move(Parms.Location);
}


// Function BP_LightManager.BP_LightManager_C.SetupExit
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CurrentExitIndex                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LightManager_C::SetupExit(int32 CurrentExitIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "SetupExit");

	Params::BP_LightManager_C_SetupExit Parms{};

	Parms.CurrentExitIndex = CurrentExitIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LightManager.BP_LightManager_C.GetTimerDelay
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Delay                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LightManager_C::GetTimerDelay(float* Delay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "GetTimerDelay");

	Params::BP_LightManager_C_GetTimerDelay Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Delay != nullptr)
		*Delay = Parms.Delay;
}


// Function BP_LightManager.BP_LightManager_C.Flicker__FinishedFunc
// (BlueprintEvent)

void ABP_LightManager_C::Flicker__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "Flicker__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LightManager.BP_LightManager_C.Flicker__UpdateFunc
// (BlueprintEvent)

void ABP_LightManager_C::Flicker__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "Flicker__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LightManager.BP_LightManager_C.MC_Flicker
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_LightManager_C::MC_Flicker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "MC_Flicker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LightManager.BP_LightManager_C.MC_TurnOff
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_LightManager_C::MC_TurnOff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "MC_TurnOff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LightManager.BP_LightManager_C.MC_TurnOn
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_LightManager_C::MC_TurnOn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "MC_TurnOn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LightManager.BP_LightManager_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_LightManager_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LightManager.BP_LightManager_C.FlickerLights
// (BlueprintCallable, BlueprintEvent)

void ABP_LightManager_C::FlickerLights()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "FlickerLights");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LightManager.BP_LightManager_C.StartFlicker
// (BlueprintCallable, BlueprintEvent)

void ABP_LightManager_C::StartFlicker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "StartFlicker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LightManager.BP_LightManager_C.EnableLights
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_LightManager_C::EnableLights()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "EnableLights");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LightManager.BP_LightManager_C.ExecuteUbergraph_BP_LightManager
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LightManager_C::ExecuteUbergraph_BP_LightManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightManager_C", "ExecuteUbergraph_BP_LightManager");

	Params::BP_LightManager_C_ExecuteUbergraph_BP_LightManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

