#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lamp

#include "Basic.hpp"

#include "BP_Lamp_classes.hpp"
#include "BP_Lamp_parameters.hpp"


namespace SDK
{

// Function BP_Lamp.BP_Lamp_C.SetPointLight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Intensity                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Lamp_C::SetPointLight(float Intensity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lamp_C", "SetPointLight");

	Params::BP_Lamp_C_SetPointLight Parms{};

	Parms.Intensity = Intensity;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Lamp.BP_Lamp_C.CheckLight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Lamp_C::CheckLight(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lamp_C", "CheckLight");

	Params::BP_Lamp_C_CheckLight Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Lamp.BP_Lamp_C.TurnON
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Lamp_C::TurnON()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lamp_C", "TurnON");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Lamp.BP_Lamp_C.TurnOFF
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Lamp_C::TurnOFF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lamp_C", "TurnOFF");

	UObject::ProcessEvent(Func, nullptr);
}

}

