#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MEGDoor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MEGDoor.BP_MEGDoor_C
// 0x0018 (0x0260 - 0x0248)
class ABP_MEGDoor_C final : public AInteractableActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0248(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         DoorOpen_Open_DA99D068436AABDF3B0C208CBB174515;    // 0x0250(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            DoorOpen__Direction_DA99D068436AABDF3B0C208CBB174515; // 0x0254(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_255[0x3];                                      // 0x0255(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     DoorOpen;                                          // 0x0258(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void DoorOpen__FinishedFunc();
	void DoorOpen__UpdateFunc();
	void OnActorUsed(class ACharacter* Character);
	void OnUsedNotify();
	void ExecuteUbergraph_BP_MEGDoor(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MEGDoor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MEGDoor_C")
	}
	static class ABP_MEGDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MEGDoor_C>();
	}
};
DUMPER7_ASSERTS_ABP_MEGDoor_C;

}

