#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TerminalSwitch

#include "Basic.hpp"

#include "BP_TerminalSwitch_classes.hpp"
#include "BP_TerminalSwitch_parameters.hpp"


namespace SDK
{

// Function BP_TerminalSwitch.BP_TerminalSwitch_C.OnRep_HasPoweredOn
// (BlueprintCallable, BlueprintEvent)

void ABP_TerminalSwitch_C::OnRep_HasPoweredOn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "OnRep_HasPoweredOn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.OnRep_IsEnabled
// (BlueprintCallable, BlueprintEvent)

void ABP_TerminalSwitch_C::OnRep_IsEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "OnRep_IsEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.SwitchLever__FinishedFunc
// (BlueprintEvent)

void ABP_TerminalSwitch_C::SwitchLever__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "SwitchLever__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.SwitchLever__UpdateFunc
// (BlueprintEvent)

void ABP_TerminalSwitch_C::SwitchLever__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "SwitchLever__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.InpActEvt_Interact_K2Node_InputActionEvent_3
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_TerminalSwitch_C::InpActEvt_Interact_K2Node_InputActionEvent_3(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "InpActEvt_Interact_K2Node_InputActionEvent_3");

	Params::BP_TerminalSwitch_C_InpActEvt_Interact_K2Node_InputActionEvent_3 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.InpActEvt_Use_K2Node_InputActionEvent_2
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_TerminalSwitch_C::InpActEvt_Use_K2Node_InputActionEvent_2(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "InpActEvt_Use_K2Node_InputActionEvent_2");

	Params::BP_TerminalSwitch_C_InpActEvt_Use_K2Node_InputActionEvent_2 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.InpActEvt_Secondary_K2Node_InputActionEvent_1
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_TerminalSwitch_C::InpActEvt_Secondary_K2Node_InputActionEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "InpActEvt_Secondary_K2Node_InputActionEvent_1");

	Params::BP_TerminalSwitch_C_InpActEvt_Secondary_K2Node_InputActionEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.InpActEvt_Back_K2Node_InputActionEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_TerminalSwitch_C::InpActEvt_Back_K2Node_InputActionEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "InpActEvt_Back_K2Node_InputActionEvent_0");

	Params::BP_TerminalSwitch_C_InpActEvt_Back_K2Node_InputActionEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.InpAxisKeyEvt_MouseWheelAxis_K2Node_InputAxisKeyEvent_1
// (BlueprintEvent)
// Parameters:
// float                                   AxisValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TerminalSwitch_C::InpAxisKeyEvt_MouseWheelAxis_K2Node_InputAxisKeyEvent_1(float AxisValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "InpAxisKeyEvt_MouseWheelAxis_K2Node_InputAxisKeyEvent_1");

	Params::BP_TerminalSwitch_C_InpAxisKeyEvt_MouseWheelAxis_K2Node_InputAxisKeyEvent_1 Parms{};

	Parms.AxisValue = AxisValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.UnPossess
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_TerminalSwitch_C::UnPossess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "UnPossess");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.MC_TurnOn
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_TerminalSwitch_C::MC_TurnOn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "MC_TurnOn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.OnFlipSwitch
// (BlueprintCallable, BlueprintEvent)

void ABP_TerminalSwitch_C::OnFlipSwitch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "OnFlipSwitch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.SetEnabled
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_TerminalSwitch_C::SetEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "SetEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.ReceivePossessed
// (Event, Public, BlueprintEvent)
// Parameters:
// class AController*                      NewController                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TerminalSwitch_C::ReceivePossessed(class AController* NewController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "ReceivePossessed");

	Params::BP_TerminalSwitch_C_ReceivePossessed Parms{};

	Parms.NewController = NewController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.OnFinished
// (BlueprintCallable, BlueprintEvent)

void ABP_TerminalSwitch_C::OnFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "OnFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.PlayError
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_TerminalSwitch_C::PlayError()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "PlayError");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.MC_Error
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_TerminalSwitch_C::MC_Error()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "MC_Error");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.OnPossess
// (Event, Public, BlueprintEvent)

void ABP_TerminalSwitch_C::OnPossess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "OnPossess");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.MC_Subtitle
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_TerminalSwitch_C::MC_Subtitle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "MC_Subtitle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TerminalSwitch.BP_TerminalSwitch_C.ExecuteUbergraph_BP_TerminalSwitch
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TerminalSwitch_C::ExecuteUbergraph_BP_TerminalSwitch(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TerminalSwitch_C", "ExecuteUbergraph_BP_TerminalSwitch");

	Params::BP_TerminalSwitch_C_ExecuteUbergraph_BP_TerminalSwitch Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

