#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WallGenerator_a

#include "Basic.hpp"

#include "BP_WallGenerator_a_classes.hpp"
#include "BP_WallGenerator_a_parameters.hpp"


namespace SDK
{

// Function BP_WallGenerator_a.BP_WallGenerator_a_C.GetRandomSeed
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class USceneComponent*                  Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRandomStream                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor)

struct FRandomStream ABP_WallGenerator_a_C::GetRandomSeed(class USceneComponent* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WallGenerator_a_C", "GetRandomSeed");

	Params::BP_WallGenerator_a_C_GetRandomSeed Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_WallGenerator_a.BP_WallGenerator_a_C.FillMeshArrIndex
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<class UStaticMesh*>&       ObjectArr                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const TArray<int32>&                    IndexArr                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_WallGenerator_a_C::FillMeshArrIndex(const TArray<class UStaticMesh*>& ObjectArr, const TArray<int32>& IndexArr)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WallGenerator_a_C", "FillMeshArrIndex");

	Params::BP_WallGenerator_a_C_FillMeshArrIndex Parms{};

	Parms.ObjectArr = std::move(ObjectArr);
	Parms.IndexArr = std::move(IndexArr);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_WallGenerator_a.BP_WallGenerator_a_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_WallGenerator_a_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WallGenerator_a_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

