#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_SoundTypes

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_SoundTypes.E_SoundTypes
// NumValues: 0x0008
enum class E_SoundTypes : uint8
{
	NewEnumerator5                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator3                           = 4,
	NewEnumerator4                           = 5,
	NewEnumerator6                           = 6,
	E_MAX                                    = 7,
};

}

