#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LightRollDoor_BP

#include "Basic.hpp"

#include "LightRollDoor_BP_classes.hpp"
#include "LightRollDoor_BP_parameters.hpp"


namespace SDK
{

// Function LightRollDoor_BP.LightRollDoor_BP_C.UpdateAnimation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   NewPosition                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ALightRollDoor_BP_C::UpdateAnimation(float NewPosition, bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LightRollDoor_BP_C", "UpdateAnimation");

	Params::LightRollDoor_BP_C_UpdateAnimation Parms{};

	Parms.NewPosition = NewPosition;

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function LightRollDoor_BP.LightRollDoor_BP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ALightRollDoor_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LightRollDoor_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LightRollDoor_BP.LightRollDoor_BP_C.MoveCollider__FinishedFunc
// (BlueprintEvent)

void ALightRollDoor_BP_C::MoveCollider__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LightRollDoor_BP_C", "MoveCollider__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LightRollDoor_BP.LightRollDoor_BP_C.MoveCollider__UpdateFunc
// (BlueprintEvent)

void ALightRollDoor_BP_C::MoveCollider__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LightRollDoor_BP_C", "MoveCollider__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LightRollDoor_BP.LightRollDoor_BP_C.BndEvt__LightRollDoor_BP_Box_K2Node_ComponentBoundEvent_4_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ALightRollDoor_BP_C::BndEvt__LightRollDoor_BP_Box_K2Node_ComponentBoundEvent_4_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LightRollDoor_BP_C", "BndEvt__LightRollDoor_BP_Box_K2Node_ComponentBoundEvent_4_ComponentBeginOverlapSignature__DelegateSignature");

	Params::LightRollDoor_BP_C_BndEvt__LightRollDoor_BP_Box_K2Node_ComponentBoundEvent_4_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LightRollDoor_BP.LightRollDoor_BP_C.BndEvt__LightRollDoor_BP_Box_K2Node_ComponentBoundEvent_5_ComponentEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALightRollDoor_BP_C::BndEvt__LightRollDoor_BP_Box_K2Node_ComponentBoundEvent_5_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LightRollDoor_BP_C", "BndEvt__LightRollDoor_BP_Box_K2Node_ComponentBoundEvent_5_ComponentEndOverlapSignature__DelegateSignature");

	Params::LightRollDoor_BP_C_BndEvt__LightRollDoor_BP_Box_K2Node_ComponentBoundEvent_5_ComponentEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LightRollDoor_BP.LightRollDoor_BP_C.ToggleCollider
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Open                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ALightRollDoor_BP_C::ToggleCollider(bool Open)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LightRollDoor_BP_C", "ToggleCollider");

	Params::LightRollDoor_BP_C_ToggleCollider Parms{};

	Parms.Open = Open;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LightRollDoor_BP.LightRollDoor_BP_C.EnableDoor
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ALightRollDoor_BP_C::EnableDoor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LightRollDoor_BP_C", "EnableDoor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LightRollDoor_BP.LightRollDoor_BP_C.ExecuteUbergraph_LightRollDoor_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALightRollDoor_BP_C::ExecuteUbergraph_LightRollDoor_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LightRollDoor_BP_C", "ExecuteUbergraph_LightRollDoor_BP");

	Params::LightRollDoor_BP_C_ExecuteUbergraph_LightRollDoor_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

