#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MP_Garage

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MP_GameMode_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MP_Garage.MP_Garage_C
// 0x0010 (0x0398 - 0x0388)
class AMP_Garage_C final : public AMP_GameMode_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_MP_Garage_C;                        // 0x0388(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         SelectedElevator;                                  // 0x0390(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ShowSubtitles();
	void OnPlayerSpawn(class ABPCharacter_Demo_C* Player);
	void ExecuteUbergraph_MP_Garage(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MP_Garage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MP_Garage_C")
	}
	static class AMP_Garage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMP_Garage_C>();
	}
};
DUMPER7_ASSERTS_AMP_Garage_C;

}

