#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MP_Garage_Bottom

#include "Basic.hpp"

#include "MP_Garage_Bottom_classes.hpp"
#include "MP_Garage_Bottom_parameters.hpp"


namespace SDK
{

// Function MP_Garage_Bottom.MP_Garage_Bottom_C.ChoosePlayerStart
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AController*                      Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class AActor* AMP_Garage_Bottom_C::ChoosePlayerStart(class AController* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Garage_Bottom_C", "ChoosePlayerStart");

	Params::MP_Garage_Bottom_C_ChoosePlayerStart Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MP_Garage_Bottom.MP_Garage_Bottom_C.LoadCheckpoints
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AMP_Garage_Bottom_C::LoadCheckpoints()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Garage_Bottom_C", "LoadCheckpoints");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MP_Garage_Bottom.MP_Garage_Bottom_C.OnPlayerSpawn
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABPCharacter_Demo_C*              Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMP_Garage_Bottom_C::OnPlayerSpawn(class ABPCharacter_Demo_C* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Garage_Bottom_C", "OnPlayerSpawn");

	Params::MP_Garage_Bottom_C_OnPlayerSpawn Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MP_Garage_Bottom.MP_Garage_Bottom_C.ExecuteUbergraph_MP_Garage_Bottom
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMP_Garage_Bottom_C::ExecuteUbergraph_MP_Garage_Bottom(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MP_Garage_Bottom_C", "ExecuteUbergraph_MP_Garage_Bottom");

	Params::MP_Garage_Bottom_C_ExecuteUbergraph_MP_Garage_Bottom Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

