#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Pipe_Exit

#include "Basic.hpp"

#include "Pipe_Exit_classes.hpp"
#include "Pipe_Exit_parameters.hpp"


namespace SDK
{

// Function Pipe_Exit.Pipe_Exit_C.OnExit
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void APipe_Exit_C::OnExit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Pipe_Exit_C", "OnExit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Pipe_Exit.Pipe_Exit_C.ExecuteUbergraph_Pipe_Exit
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APipe_Exit_C::ExecuteUbergraph_Pipe_Exit(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Pipe_Exit_C", "ExecuteUbergraph_Pipe_Exit");

	Params::Pipe_Exit_C_ExecuteUbergraph_Pipe_Exit Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

