#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RollDoor_ABP

#include "Basic.hpp"

#include "RollDoor_ABP_classes.hpp"
#include "RollDoor_ABP_parameters.hpp"


namespace SDK
{

// Function RollDoor_ABP.RollDoor_ABP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void URollDoor_ABP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RollDoor_ABP_C", "AnimGraph");

	Params::RollDoor_ABP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function RollDoor_ABP.RollDoor_ABP_C.ExecuteUbergraph_RollDoor_ABP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URollDoor_ABP_C::ExecuteUbergraph_RollDoor_ABP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RollDoor_ABP_C", "ExecuteUbergraph_RollDoor_ABP");

	Params::RollDoor_ABP_C_ExecuteUbergraph_RollDoor_ABP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

