#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SplashScreen_MediaSoundActor

#include "Basic.hpp"

#include "SplashScreen_MediaSoundActor_classes.hpp"
#include "SplashScreen_MediaSoundActor_parameters.hpp"


namespace SDK
{

// Function SplashScreen_MediaSoundActor.SplashScreen_MediaSoundActor_C.AttachMediaPlayer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMediaPlayer*                     NewMediaPlayer                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASplashScreen_MediaSoundActor_C::AttachMediaPlayer(class UMediaPlayer* NewMediaPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreen_MediaSoundActor_C", "AttachMediaPlayer");

	Params::SplashScreen_MediaSoundActor_C_AttachMediaPlayer Parms{};

	Parms.NewMediaPlayer = NewMediaPlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SplashScreen_MediaSoundActor.SplashScreen_MediaSoundActor_C.ExecuteUbergraph_SplashScreen_MediaSoundActor
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASplashScreen_MediaSoundActor_C::ExecuteUbergraph_SplashScreen_MediaSoundActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreen_MediaSoundActor_C", "ExecuteUbergraph_SplashScreen_MediaSoundActor");

	Params::SplashScreen_MediaSoundActor_C_ExecuteUbergraph_SplashScreen_MediaSoundActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

