#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SplashScreenMap

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SplashScreenMap.SplashScreenMap_C
// 0x0010 (0x0238 - 0x0228)
class ASplashScreenMap_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ASplashScreen_MediaSoundActor_C*        SplashScreen_MediaSoundActor_4_ExecuteUbergraph_SplashScreenMap_RefProperty; // 0x0230(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void OnFinishedSplashScreens();
	void ExecuteUbergraph_SplashScreenMap(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SplashScreenMap_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SplashScreenMap_C")
	}
	static class ASplashScreenMap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASplashScreenMap_C>();
	}
};
DUMPER7_ASSERTS_ASplashScreenMap_C;

}

