#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SplashScreenMap

#include "Basic.hpp"

#include "SplashScreenMap_classes.hpp"
#include "SplashScreenMap_parameters.hpp"


namespace SDK
{

// Function SplashScreenMap.SplashScreenMap_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASplashScreenMap_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreenMap_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SplashScreenMap.SplashScreenMap_C.OnFinishedSplashScreens
// (BlueprintCallable, BlueprintEvent)

void ASplashScreenMap_C::OnFinishedSplashScreens()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreenMap_C", "OnFinishedSplashScreens");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SplashScreenMap.SplashScreenMap_C.ExecuteUbergraph_SplashScreenMap
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASplashScreenMap_C::ExecuteUbergraph_SplashScreenMap(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreenMap_C", "ExecuteUbergraph_SplashScreenMap");

	Params::SplashScreenMap_C_ExecuteUbergraph_SplashScreenMap Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

