#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SplashScreen_UI

#include "Basic.hpp"

#include "SplashScreen_UI_classes.hpp"
#include "SplashScreen_UI_parameters.hpp"


namespace SDK
{

// Function SplashScreen_UI.SplashScreen_UI_C.Finished_D31BF3F246FE87473995198D7511F578
// (BlueprintCallable, BlueprintEvent)

void USplashScreen_UI_C::Finished_D31BF3F246FE87473995198D7511F578()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreen_UI_C", "Finished_D31BF3F246FE87473995198D7511F578");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SplashScreen_UI.SplashScreen_UI_C.Finished_1B0E4D10450F17056185DF8F68ED901C
// (BlueprintCallable, BlueprintEvent)

void USplashScreen_UI_C::Finished_1B0E4D10450F17056185DF8F68ED901C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreen_UI_C", "Finished_1B0E4D10450F17056185DF8F68ED901C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SplashScreen_UI.SplashScreen_UI_C.Finished_262FC8A444B59E2C880FAAAD09BCB060
// (BlueprintCallable, BlueprintEvent)

void USplashScreen_UI_C::Finished_262FC8A444B59E2C880FAAAD09BCB060()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreen_UI_C", "Finished_262FC8A444B59E2C880FAAAD09BCB060");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SplashScreen_UI.SplashScreen_UI_C.OnFinishSMLogo
// (BlueprintCallable, BlueprintEvent)

void USplashScreen_UI_C::OnFinishSMLogo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreen_UI_C", "OnFinishSMLogo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SplashScreen_UI.SplashScreen_UI_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USplashScreen_UI_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreen_UI_C", "PreConstruct");

	Params::SplashScreen_UI_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SplashScreen_UI.SplashScreen_UI_C.PlaySplashScreens
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASplashScreen_MediaSoundActor_C*  SoundActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USplashScreen_UI_C::PlaySplashScreens(class ASplashScreen_MediaSoundActor_C* SoundActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreen_UI_C", "PlaySplashScreens");

	Params::SplashScreen_UI_C_PlaySplashScreens Parms{};

	Parms.SoundActor = SoundActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SplashScreen_UI.SplashScreen_UI_C.OnFinishBBILogo
// (BlueprintCallable, BlueprintEvent)

void USplashScreen_UI_C::OnFinishBBILogo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreen_UI_C", "OnFinishBBILogo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SplashScreen_UI.SplashScreen_UI_C.ExecuteUbergraph_SplashScreen_UI
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USplashScreen_UI_C::ExecuteUbergraph_SplashScreen_UI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SplashScreen_UI_C", "ExecuteUbergraph_SplashScreen_UI");

	Params::SplashScreen_UI_C_ExecuteUbergraph_SplashScreen_UI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

