#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SplashScreen_MediaSoundActor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SplashScreen_MediaSoundActor.SplashScreen_MediaSoundActor_C
// 0x0020 (0x0240 - 0x0220)
class ASplashScreen_MediaSoundActor_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UMediaSoundComponent*                   MediaSound;                                        // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMediaPlayer*                           Media;                                             // 0x0238(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AttachMediaPlayer(class UMediaPlayer* NewMediaPlayer);
	void ExecuteUbergraph_SplashScreen_MediaSoundActor(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SplashScreen_MediaSoundActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SplashScreen_MediaSoundActor_C")
	}
	static class ASplashScreen_MediaSoundActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASplashScreen_MediaSoundActor_C>();
	}
};
DUMPER7_ASSERTS_ASplashScreen_MediaSoundActor_C;

}

