#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CardMenu

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CardMenu.WBP_CardMenu_C
// 0x0010 (0x0270 - 0x0260)
class UWBP_CardMenu_C final : public UUserWidget
{
public:
	class UScrollBox*                             ScrollBoxCards;                                    // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAC_CardReaderPlayer_C*                 ComponentPlayer;                                   // 0x0268(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void Update();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CardMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CardMenu_C")
	}
	static class UWBP_CardMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CardMenu_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CardMenu_C;

}

