#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CardInfo

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_CardInfo.WBP_CardInfo_C.Get_TextBlockInteract_Text_0
// 0x0018 (0x0018 - 0x0000)
struct WBP_CardInfo_C_Get_TextBlockInteract_Text_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_WBP_CardInfo_C_Get_TextBlockInteract_Text_0;

}

