#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EasyCardItem

#include "Basic.hpp"

#include "WBP_EasyCardItem_classes.hpp"
#include "WBP_EasyCardItem_parameters.hpp"


namespace SDK
{

// Function WBP_EasyCardItem.WBP_EasyCardItem_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_EasyCardItem_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EasyCardItem_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_EasyCardItem.WBP_EasyCardItem_C.BndEvt__WBP_EasyCardItem_ButtonEnter_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_EasyCardItem_C::BndEvt__WBP_EasyCardItem_ButtonEnter_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EasyCardItem_C", "BndEvt__WBP_EasyCardItem_ButtonEnter_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_EasyCardItem.WBP_EasyCardItem_C.BndEvt__WBP_EasyCardItem_ButtonDrop_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_EasyCardItem_C::BndEvt__WBP_EasyCardItem_ButtonDrop_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EasyCardItem_C", "BndEvt__WBP_EasyCardItem_ButtonDrop_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_EasyCardItem.WBP_EasyCardItem_C.ExecuteUbergraph_WBP_EasyCardItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_EasyCardItem_C::ExecuteUbergraph_WBP_EasyCardItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EasyCardItem_C", "ExecuteUbergraph_WBP_EasyCardItem");

	Params::WBP_EasyCardItem_C_ExecuteUbergraph_WBP_EasyCardItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

