#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CardReaderDisplay

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "F_CardInfo_structs.hpp"
#include "UMG_classes.hpp"
#include "E_CodeReaderStatus_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CardReaderDisplay.WBP_CardReaderDisplay_C
// 0x00E0 (0x0340 - 0x0260)
class UWBP_CardReaderDisplay_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             AccessTypePersonal;                                // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             AccessTypePersonal_1;                              // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                BorderInfo;                                        // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextStatus;                                        // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         InputCode;                                         // 0x0288(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_28C[0x4];                                      // 0x028C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Code;                                              // 0x0290(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 VisibleCode;                                       // 0x02A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	int32                                         cfg_LengthCode;                                    // 0x02B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B4[0x4];                                      // 0x02B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FF_CardInfo                            CardInfo;                                          // 0x02B8(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class ABP_CardReader_C*                       CardReader;                                        // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           TimerDisplay;                                      // 0x0320(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FText                                   InteractTextHint;                                  // 0x0328(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void CheckCodeAndAccess(const class FString& Code_0, int32* Result);
	class FText Get_TextBlockPressKey_Text_0();
	void Switch_Panels(E_CodeReaderStatus Status);
	void UpdateReaderInfo();
	void UpdateCardInfo(const struct FF_CardInfo& CardInfo_0);
	void Check_Code();
	void ResetInput();
	void EnterCode(int32 int_0);
	void Construct();
	void DisplatTimeOut();
	void ApplayEnter(int32 Result);
	void ExecuteUbergraph_WBP_CardReaderDisplay(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CardReaderDisplay_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CardReaderDisplay_C")
	}
	static class UWBP_CardReaderDisplay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CardReaderDisplay_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CardReaderDisplay_C;

}

