#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CardReaderDisplay_MEG

#include "Basic.hpp"

#include "E_CodeReaderStatus_structs.hpp"
#include "F_CardInfo_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function WBP_CardReaderDisplay_MEG.WBP_CardReaderDisplay_MEG_C.CheckCodeAndAccess
// 0x0020 (0x0020 - 0x0000)
struct WBP_CardReaderDisplay_MEG_C_CheckCodeAndAccess final
{
public:
	class FString                                 Code_0;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	int32                                         Result;                                            // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x0016(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue_1;          // 0x0017(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_Contains_ReturnValue_1;             // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_CardReaderDisplay_MEG_C_CheckCodeAndAccess;

// Function WBP_CardReaderDisplay_MEG.WBP_CardReaderDisplay_MEG_C.Get_TextBlockPressKey_Text_0
// 0x0018 (0x0018 - 0x0000)
struct WBP_CardReaderDisplay_MEG_C_Get_TextBlockPressKey_Text_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_WBP_CardReaderDisplay_MEG_C_Get_TextBlockPressKey_Text_0;

// Function WBP_CardReaderDisplay_MEG.WBP_CardReaderDisplay_MEG_C.Switch Panels
// 0x0002 (0x0002 - 0x0000)
struct WBP_CardReaderDisplay_MEG_C_Switch_Panels final
{
public:
	E_CodeReaderStatus                            Status;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_CardReaderDisplay_MEG_C_Switch_Panels;

// Function WBP_CardReaderDisplay_MEG.WBP_CardReaderDisplay_MEG_C.UpdateReaderInfo
// 0x0020 (0x0020 - 0x0000)
struct WBP_CardReaderDisplay_MEG_C_UpdateReaderInfo final
{
public:
	class FString                                 Personal_type_list;                                // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Personal_individual_list;                          // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CardReaderDisplay_MEG_C_UpdateReaderInfo;

// Function WBP_CardReaderDisplay_MEG.WBP_CardReaderDisplay_MEG_C.UpdateCardInfo
// 0x0060 (0x0060 - 0x0000)
struct WBP_CardReaderDisplay_MEG_C_UpdateCardInfo final
{
public:
	struct FF_CardInfo                            CardInfo_0;                                        // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CardReaderDisplay_MEG_C_UpdateCardInfo;

// Function WBP_CardReaderDisplay_MEG.WBP_CardReaderDisplay_MEG_C.Check Code
// 0x0008 (0x0008 - 0x0000)
struct WBP_CardReaderDisplay_MEG_C_Check_Code final
{
public:
	int32                                         CallFunc_Len_ReturnValue;                          // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_CardReaderDisplay_MEG_C_Check_Code;

// Function WBP_CardReaderDisplay_MEG.WBP_CardReaderDisplay_MEG_C.ResetInput
// 0x0020 (0x0020 - 0x0000)
struct WBP_CardReaderDisplay_MEG_C_ResetInput final
{
public:
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_WBP_CardReaderDisplay_MEG_C_ResetInput;

// Function WBP_CardReaderDisplay_MEG.WBP_CardReaderDisplay_MEG_C.EnterCode
// 0x0058 (0x0058 - 0x0000)
struct WBP_CardReaderDisplay_MEG_C_EnterCode final
{
public:
	int32                                         int_0;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Right_ReturnValue;                        // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_2;              // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CardReaderDisplay_MEG_C_EnterCode;

// Function WBP_CardReaderDisplay_MEG.WBP_CardReaderDisplay_MEG_C.ApplayEnter
// 0x0004 (0x0004 - 0x0000)
struct WBP_CardReaderDisplay_MEG_C_ApplayEnter final
{
public:
	int32                                         Result;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CardReaderDisplay_MEG_C_ApplayEnter;

// Function WBP_CardReaderDisplay_MEG.WBP_CardReaderDisplay_MEG_C.ExecuteUbergraph_WBP_CardReaderDisplay_MEG
// 0x0028 (0x0028 - 0x0000)
struct WBP_CardReaderDisplay_MEG_C_ExecuteUbergraph_WBP_CardReaderDisplay_MEG final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_Result;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x000C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0020(0x0008)(NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CardReaderDisplay_MEG_C_ExecuteUbergraph_WBP_CardReaderDisplay_MEG;

}

