#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CardInfo

#include "Basic.hpp"

#include "WBP_CardInfo_classes.hpp"
#include "WBP_CardInfo_parameters.hpp"


namespace SDK
{

// Function WBP_CardInfo.WBP_CardInfo_C.Get_TextBlockInteract_Text_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_CardInfo_C::Get_TextBlockInteract_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CardInfo_C", "Get_TextBlockInteract_Text_0");

	Params::WBP_CardInfo_C_Get_TextBlockInteract_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

