#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ServerConnectionErrorFlow

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_ServerConnectionErrorFlow.BP_ServerConnectionErrorFlow_C.ExecuteUbergraph_BP_ServerConnectionErrorFlow
// 0x0050 (0x0050 - 0x0000)
struct BP_ServerConnectionErrorFlow_C_ExecuteUbergraph_BP_ServerConnectionErrorFlow final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0008(0x0018)()
	class FText                                   Temp_text_Variable_1;                              // 0x0020(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x0038(0x0018)()
};
DUMPER7_ASSERTS_BP_ServerConnectionErrorFlow_C_ExecuteUbergraph_BP_ServerConnectionErrorFlow;

}

