#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ServerConnectionErrorFlow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ServerConnectionErrorFlow.BP_ServerConnectionErrorFlow_C
// 0x0010 (0x00B8 - 0x00A8)
class UBP_ServerConnectionErrorFlow_C final : public UFancyUserFlow
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          bOnline;                                           // 0x00B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_BP_ServerConnectionErrorFlow(int32 EntryPoint);
	void Run();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ServerConnectionErrorFlow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ServerConnectionErrorFlow_C")
	}
	static class UBP_ServerConnectionErrorFlow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ServerConnectionErrorFlow_C>();
	}
};
DUMPER7_ASSERTS_UBP_ServerConnectionErrorFlow_C;

}

